backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

site_url: https://sprightly-sable-226e9e.netlify.app

collections:
  - name: "cakes"
    label: "Cakes"
    folder: "content/cakes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Flavor", name: "flavor", widget: "string", required: false }
      - { label: "Size", name: "size", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Published", name: "published", widget: "boolean", default: true }
